name: ${project.name}
main: ${project.groupId}.${project.artifactId}.UHC
version: ${project.version}
author: ghowden/Eluinhost
database: false
soft-depend: [ProtocolLib]
commands:
  showhealth:
    permission: uhc.command.showhealth
  ghead:
    permission: uhc.command.ghead
  border:
    permission: uhc.command.border
  heal:
    permission: uhc.command.heal
  feed:
    permission: uhc.command.feed
  ci:
    permission: uhc.command.ci
  clearxp:
    permission: uhc.command.clearxp
  reset:
    permission: uhc.command.reset
  cleareffects:
    permission: uhc.command.cleareffects
  teams:
    permission: uhc.command.teams
  team:
    permission: uhc.command.team
  noteam:
    permission: uhc.command.noteam
  pmt:
    permission: uhc.command.pmt
  randomteams:
    permission: uhc.command.randomteams
  clearteams:
    permission: uhc.command.clearteams
  uhc:
    permission: uhc.command.uhc
  timer:
    permission: uhc.command.timer
  tpp:
    permission: uhc.command.tpp
  teamrequest:
    permission: uhc.command.teamrequest
  tc:
    permission: uhc.command.tc
  h:
    permission: uhc.command.health
permissions:
  uhc.command.showhealth:
    default: op
  uhc.command.ghead:
    default: op
  uhc.command.border:
    default: op
  uhc.command.heal:
    default: op
  uhc.command.ci:
    default: op
  uhc.command.clearxp:
    default: op
  uhc.command.reset:
    default: op
  uhc.command.cleareffects:
    default: op
  uhc.command.teams:
    default: true
  uhc.command.team:
    default: op
  uhc.command.noteam:
    default: op
  uhc.command.pmt:
    default: true
  uhc.command.randomteams:
    default: op
  uhc.command.clearteams:
    default: op
  uhc.broadcast.netherdisable:
    default: op
  uhc.command.uhc:
    default: true
  uhc.command.uhc.admin:
    default: op
  uhc.command.timer:
    default: op
  uhc.command.tpp:
    default: op
  uhc.command.teamrequest:
    default: true
  uhc.command.teamrequestadmin:
    default: op
  uhc.command.tc:
    default: true
  uhc.command.health:
    default: true