name: ${project.name}
main: ${project.groupId}.${project.artifactId}.UHC
version: ${project.version}
author: ghowden/Eluinhost
database: false
commands:
  showhealth:
    permission: uhc.command.showhealth
  ghead:
    permission: uhc.command.ghead
  addons:
    permission: uhc.command.addons
  border:
    permission: uhc.command.border
  heal:
    permission: uhc.command.heal
permissions:
  uhc.command.showhealth:
    default: op
  uhc.command.ghead:
    default: op
  uhc.command.addons:
    default: true
  uhc.command.border:
    default: op
  uhc.command.heal:
    default: op